---
- name: K3s 설치 여부 확인 (중복 설치 방지)
  command: which k3s
  register: k3s_installed
  ignore_errors: yes
  changed_when: false

- name: K3s Primary Node 설치 스크립트 다운로드 및 실행
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init" sh -
  when: k3s_installed.rc != 0 # k3s가 없을 때만 실행

- name: K3s 서비스가 정상적으로 실행 중인지 확인
  systemd:
    name: k3s
    state: started
    enabled: yes
# 1. Node Exporter 다운로드 및 압축 해제
- name: Download and Unarchive Node Exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]

# 2. systemd 서비스 등록 (서버 꺼져도 자동 실행되게)
- name: Create Node Exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      [Service]
      ExecStart=/usr/local/bin/node_exporter
      Restart=always
      [Install]
      WantedBy=multi-user.target

# 3. 서비스 시작 및 활성화
- name: Start Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
